[package]
name = "life"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[dependencies]
egui = "0.27.2"
eframe = "0.27.2"
env_logger = { version = "0.11.1", default-features = false, features = [
    "auto-color",
    "humantime",
] }
rand = "0.8.4"
rand_chacha = "0.3.0"
